### ISSUE TITLE
Stream updated by AMQP 0.9.1 casuses ReadCompositeHeader Invalid type 80

### ISSUE THREAD

**Issue by thaoula** [coders51/rabbitmq-stream-js-client#181]
Hi Team,

I am currently attempting to move some of our stream processing from Rascal AMQP 0.9.1 to your new client. 

I am having issues trying to read the stream when it is updated by AMQP 0.9.1. From my understanding this should be a valid use case.  https://blog.rabbitmq.com/posts/2021/10/rabbitmq-streams-interoperability/

There are two issues here. 
- The application crashes and I don't know how to catch this error to prevent it.
- The ReadCompositeHeader Invalid type 80 occurs.

```
Error: ReadCompositeHeader Invalid type 80
    at decodeFormatCode (/home/app/node_modules/rabbitmq-stream-js-client/dist/response_decoder.js:360:19)
    at /home/app/node_modules/rabbitmq-stream-js-client/dist/amqp10/messageAnnotations.js:13:75
    at Array.reduce (<anonymous>)
    at Annotations.parse (/home/app/node_modules/rabbitmq-stream-js-client/dist/amqp10/messageAnnotations.js:9:46)
    at decodeMessageAnnotations (/home/app/node_modules/rabbitmq-stream-js-client/dist/response_decoder.js:238:45)
    at decodeMessage (/home/app/node_modules/rabbitmq-stream-js-client/dist/response_decoder.js:197:38)
    at decodeDeliverResponse (/home/app/node_modules/rabbitmq-stream-js-client/dist/response_decoder.js:170:27)
    at decodeResponse (/home/app/node_modules/rabbitmq-stream-js-client/dist/response_decoder.js:64:64)
    at decode (/home/app/node_modules/rabbitmq-stream-js-client/dist/response_decoder.js:58:41)
    at ResponseDecoder.add (/home/app/node_modules/rabbitmq-stream-js-client/dist/response_decoder.js:524:45)
    at Connection.received (/home/app/node_modules/rabbitmq-stream-js-client/dist/connection.js:211:22)
    at Socket.<anonymous> (/home/app/node_modules/rabbitmq-stream-js-client/dist/connection.js:99:22)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Regards,
Tarek

**Comment by tarzacodes** [comment]
Fix is almost done - v0.3.1 will contain the necessary fix. Let us know if you experience other problems or your specific issue is not solved!

**Comment by thaoula** [comment]
Many thanks for your help @tarzacodes!!!

**Comment by thaoula** [comment]
Hi @tarzacodes, 

Just wondering, what is the correct way to handle unexpected errors coming from the internals of this library.

I don't want errors to actually crash the node process. Is there a listener or something that I should hook into?

Regards,
Tarek
